INSERT INTO _assessment_titles VALUES (1, "Letter-Word Identification");
INSERT INTO _assessment_titles VALUES (2, "Reading Fluency");
INSERT INTO _assessment_titles VALUES (3, "Story Recall");
INSERT INTO _assessment_titles VALUES (4, "Understanding Directions");
INSERT INTO _assessment_titles VALUES (5, "Calculations");
INSERT INTO _assessment_titles VALUES (6, "Math Fluency");
INSERT INTO _assessment_titles VALUES (7, "Spelling");
INSERT INTO _assessment_titles VALUES (8, "Writing Fluency");
INSERT INTO _assessment_titles VALUES (9, "Passage Comprehension");
INSERT INTO _assessment_titles VALUES (10, "Applied Problems");
INSERT INTO _assessment_titles VALUES (11, "Writing Samples");
INSERT INTO _assessment_titles VALUES (12, "Story Recall - Delayed");
INSERT INTO _assessment_titles VALUES (13, "Word Attack");
INSERT INTO _assessment_titles VALUES (14, "Picture Vocabulary");
INSERT INTO _assessment_titles VALUES (15, "Oral Comprehension");
INSERT INTO _assessment_titles VALUES (16, "Editing");
INSERT INTO _assessment_titles VALUES (17, "Reading Vocabulary");
INSERT INTO _assessment_titles VALUES (18, "Quantitative Concepts");
INSERT INTO _assessment_titles VALUES (19, "Academic Knowledge");
INSERT INTO _assessment_titles VALUES (20, "Spelling of Sounds");
INSERT INTO _assessment_titles VALUES (21, "Sound Awareness");
INSERT INTO _assessment_titles VALUES (22, "Punctuation and Capitalization");